### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Elliter** [4el0ve4ik/CryCheat#1]
Привет.
Getting error on start x64 version
@4el0ve4ik 
Screenshot - https://sun9-49.userapi.com/impg/6Kbm_-OAwrgj3rB2Bsnxy_H-S2MnfeqZNcdIAw/cO5cfjqjIC0.jpg?size=336x151&quality=96&sign=03b217f73aa5e59713f8f0b3eb3c16a2&type=album

**Comment by 4el0ve4ik** [comment]
Hi, everything is working on https://torrent-igruha.ru/1151-crysis-1-ot-mehanikov-pc-2.html
I checked.

**Comment by 4el0ve4ik** [comment]
Hi, everything is working on https://torrent-igruha.ru/1151-crysis-1-ot-mehanikov-pc-2.html
I checked.
